"""
TOOLS_META describes all 20 tools, their allowed mime types, whether they are heavy,
and per-tool constraints. This is a direct translation from the original JSON.
"""
TOOLS_META = {
    # PDF tools
    "merge-pdf": {
        "slug": "merge-pdf",
        "name": "Merge PDF",
        "category": "pdf",
        "heavy": True,
        "max_input_files": 20,
        "max_size_bytes": 200 * 1024 * 1024,
        "allowed_mime_types": ["application/pdf"],
    },
    "split-pdf": {
        "slug": "split-pdf",
        "name": "Split PDF",
        "category": "pdf",
        "heavy": True,
        "max_input_files": 1,
        "allowed_mime_types": ["application/pdf"],
    },
    "compress-pdf": {
        "slug": "compress-pdf",
        "name": "Compress PDF",
        "category": "pdf",
        "heavy": True,
        "max_input_files": 1,
        "allowed_mime_types": ["application/pdf"],
    },
    "pdf-resize-size": {
        "slug": "pdf-resize-size",
        "name": "PDF Resize (KB/MB)",
        "category": "pdf",
        "heavy": True,
        "max_input_files": 1,
        "allowed_mime_types": ["application/pdf"],
        "options": {"targetSizeKB": {"type": "number"}},
    },
    "pdf-to-image": {
        "slug": "pdf-to-image",
        "name": "PDF to Image",
        "category": "pdf",
        "heavy": True,
        "max_input_files": 1,
        "allowed_mime_types": ["application/pdf"],
        "options": {"format": {"type": "enum", "enumValues": ["png", "jpeg"]}},
    },
    "image-to-pdf": {
        "slug": "image-to-pdf",
        "name": "Image to PDF",
        "category": "pdf",
        "heavy": False,
        "max_input_files": 20,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
    },
    "rotate-pdf": {
        "slug": "rotate-pdf",
        "name": "Rotate PDF",
        "category": "pdf",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["application/pdf"],
        "options": {"angle": {"type": "number"}},
    },
    "delete-pages": {
        "slug": "delete-pages",
        "name": "Delete Pages",
        "category": "pdf",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["application/pdf"],
        "options": {"pages": {"type": "string"}},
    },
    "extract-pages": {
        "slug": "extract-pages",
        "name": "Extract Pages",
        "category": "pdf",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["application/pdf"],
        "options": {"pages": {"type": "string"}},
    },
    "add-watermark": {
        "slug": "add-watermark",
        "name": "Add Watermark",
        "category": "pdf",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["application/pdf", "image/png", "image/jpeg"],
        "options": {"watermarkText": {"type": "string"}},
    },
    # Image tools
    "image-compressor": {
        "slug": "image-compressor",
        "name": "Image Compressor",
        "category": "image",
        "heavy": True,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
    },
    "image-resize-kb": {
        "slug": "image-resize-kb",
        "name": "Image Resizer (KB / MB)",
        "category": "image",
        "heavy": True,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
        "options": {"targetSizeKB": {"type": "number"}},
    },
    "image-resize-dim": {
        "slug": "image-resize-dim",
        "name": "Image Resizer (Dimensions)",
        "category": "image",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
        "options": {"width": {"type": "number"}, "height": {"type": "number"}},
    },
    "crop-image": {
        "slug": "crop-image",
        "name": "Crop Image",
        "category": "image",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
        "options": {"left": {"type": "number"}, "top": {"type": "number"}, "width": {"type": "number"}, "height": {"type": "number"}},
    },
    "convert-image": {
        "slug": "convert-image",
        "name": "Convert Image (JPG / PNG / WEBP)",
        "category": "image",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
        "options": {"format": {"type": "enum", "enumValues": ["jpeg", "png", "webp"]}},
    },
    "rotate-image": {
        "slug": "rotate-image",
        "name": "Rotate Image",
        "category": "image",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
        "options": {"angle": {"type": "number"}},
    },
    "flip-image": {
        "slug": "flip-image",
        "name": "Flip Image",
        "category": "image",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
        "options": {"axis": {"type": "enum", "enumValues": ["horizontal", "vertical"]}},
    },
    "image-watermark": {
        "slug": "image-watermark",
        "name": "Image Watermark",
        "category": "image",
        "heavy": False,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
        "options": {"watermarkText": {"type": "string"}},
    },
    "merge-images": {
        "slug": "merge-images",
        "name": "Merge Images",
        "category": "image",
        "heavy": True,
        "max_input_files": 20,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
    },
    "split-image-grid": {
        "slug": "split-image-grid",
        "name": "Split Image (Grid)",
        "category": "image",
        "heavy": True,
        "max_input_files": 1,
        "allowed_mime_types": ["image/jpeg", "image/png", "image/webp"],
        "options": {"rows": {"type": "number"}, "cols": {"type": "number"}},
    },
}
